parameters:
  api_key: ""

services:
  client:
    class: Silktide\SemRushApi\Client
    arguments:
      - "%api_key%"
      - "@request.factory"
      - "@result.factory"
      - "@response.parser"
      - "@url.builder"
      - "@guzzle.client"
    calls:
      - method: setCache
        arguments:
          - "@cache.client"

  request.factory:
    class: Silktide\SemRushApi\Model\Factory\RequestFactory

  result.factory:
    class: Silktide\SemRushApi\Model\Factory\ResultFactory
    arguments:
      - "@row.factory"

  response.parser:
    class: Silktide\SemRushApi\Helper\ResponseParser

  url.builder:
    class: Silktide\SemRushApi\Helper\UrlBuilder

  row.factory:
    class: Silktide\SemRushApi\Model\Factory\RowFactory

  cache.client:
    class: Silktide\SemRushApi\Cache\MemoryCache

  guzzle.client:
    class: GuzzleHttp\Client