parameters:
  api_key: ""
  cache.prefix: "semrush_"

services:
  client:
    class: Silktide\SemRushApi\Client
    arguments:
      - "%api_key%"
      - "@request.factory"
      - "@response.parser"
      - "@result.factory"
      - "@url.builder"
      - "@guzzle.client"
    calls:
      - method: "setCache"
        arguments:
          - "@cache"
          - "@cache.lifetime"
          - "%cache.prefix%"

  request.factory:
    class: Silktide\SemRushApi\Model\Factory\RequestFactory

  result.factory:
    class: Silktide\SemRushApi\Model\Factory\ResultFactory
    arguments:
      - "@row.factory"

  response.parser:
    class: Silktide\SemRushApi\Helper\ResponseParser

  url.builder:
    class: Silktide\SemRushApi\Helper\UrlBuilder

  row.factory:
    class: Silktide\SemRushApi\Model\Factory\RowFactory

  guzzle.client:
    class: GuzzleHttp\Client

  cache:
    class: Cache\Adapter\PHPArray\ArrayCachePool

  cache.lifetime:
    class: \DateInterval
    arguments:
      - "P30D" # 30 days